### ISSUE TITLE
ROSSCO-Apollo steering PID controller questions

### ISSUE THREAD

**Issue by FlorentRevest** [PolySync/roscco#14]
While looking at the code of rossco_apollo, I noticed [the usage of a "PID" controller](https://github.com/PolySync/roscco/blob/master/example/roscco_apollo.cpp#L127) for a closed-loop control of steering commands.
However, in each call of _closedLoopControl_, a new local variable _state_ is initialized using [createPIDState](https://github.com/PolySync/roscco/blob/master/src/pid_control.cpp#L3) which always re-initializes the _integral_ and _pre_error_ terms to 0. The controller doesn't seem to keep track of its previous states.
This means that every call to pidController will compute an [integral term equal to the error](https://github.com/PolySync/roscco/blob/master/src/pid_control.cpp#L19) and a [derivative term equal to the error](https://github.com/PolySync/roscco/blob/master/src/pid_control.cpp#L33) as well. Eventually, this means that the PID controller of parameters Kp, Ki, Kd is equivalent to a P controller of parameter (Kp+Ki+Kd).

My questions are:
- Why would we need a PID controller on the first place? Wouldn't Apollo's control module be enough to generate smooth steering commands?
- Am I missing something in the logic of this code? If not, why is the PID controller equivalent to a P controller ?
- I understand that this is a code example but Apollo's [ControlCommand variables also come with a "steering_rate"](https://github.com/ApolloAuto/apollo/blob/master/modules/canbus/vehicle/vehicle_controller.cc#L140) command that is currently ignored by roscco_apollo. What would be the best way to use OSCC to take into account the steering rate ?

**Comment by ghost** [comment]
You are right, the current version of the controller work as a P controller and not as a PID. Thank you for noticing that. We will make sure to correct that for the next release.

DriveKit/OSCC expects a torque command for the steering. Apollo only provides steering angle and rate commands. The controller role is to evaluate a torque command to feed to DriveKit/OSCC from Apollo's steering angle command. Yes, we could also use the steering rate command to complete/improve the controller.

**Comment by wsung1** [comment]
Hi, @bbidault2, @FlorentRevest,
Would you share with me, if you have any updates specifically on how to convert a steering angle command (from Apollo, Autoware, etc) to a steering torque command (to roscco in DriveKit)?
Thanks in advance!

**Comment by FlorentRevest** [comment]
In the end I just ended up using the angle control command of the DriveKit. It is not part of oscc but is an additional feature of the drivekit that does the control for you and I found it worked well enough

**Comment by wsung1** [comment]
@FlorentRevest, thanks for your reply. If you don't mind, would you please tell me a little bit more about that additional feature of DriveKit? Is it described in your github repo or somewhere else? I think I have to follow the way you walked through. Thanks in advance!

**Comment by FlorentRevest** [comment]
This feature was documented as part of the DriveKit.
You can find my Apollo implementation here

https://github.com/nap-lab/apollo/blob/v3.0/modules/canbus/vehicle/niro/protocol/steering_angle_command_b8.cc

**Comment by wsung1** [comment]
@FlorentRevest, thanks for your sharing! :)
